//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectWeb_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mSTATUS
    {
        public mSTATUS()
        {
            this.USERS = new HashSet<USERS>();
        }
    
        public int idStatus { get; set; }
        public string Status { get; set; }
    
        public virtual ICollection<USERS> USERS { get; set; }
    }
}
